---
- name: Ensure module br_netfilter autostart
  copy:
    src: modules-load.d/k8s.conf
    dest: /etc/modules-load.d/k8s.conf
    mode: "0640"
  become: true

- name: Ensure br_netfilter is loaded
  modprobe:
    name: br_netfilter
    state: present
  become: true

- name: Ensure net.bridge.bridge-nf-call-iptables is set to 1
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf
    sysctl_set: true
  with_items:
    - {name: net.ipv4.ip_forward, value: 1}
    - {name: net.bridge.bridge-nf-call-ip6tables, value: 1}
    - {name: net.bridge.bridge-nf-call-iptables, value: 1}
  become: true
