---
- name: Install packages required by kubetools
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - bash-completion
    state: present
    update_cache: true
  become: true

- name: Add an Apt signing key for kubernetes
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present
  become: true

# unfortunately there is no repo for focal [kubernetes-focal] dist (ubuntu 20.04)
# repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-{{ ansible_facts['lsb']['codename'] }} main
- name: Add kubernetes to apt repository
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    update_cache: true
  become: true

- name: Ensure apt pinning for kubeadm is set
  template:
    src: k8s.pref.j2
    dest: /etc/apt/preferences.d/k8s.pref
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Allow kubetools being upgraded
  dpkg_selections:
    name: "{{ item }}"
    selection: install
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  become: true
  when: |
    kubeadm_version_reinstall | bool

- name: Install kubetools
  apt:
    name:
      - "kubelet={{ kubeadm_version_kubelet }}"
      - "kubeadm={{ kubeadm_version_kubeadm }}"
      - "kubectl={{ kubeadm_version_kubectl }}"
      - cri-tools
    state: present
    update_cache: true
  become: true

- name: Prevent kubetools from being upgraded
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  become: true

- name: Template kubelet default
  template:
    src: kubelet.j2
    dest: /etc/default/kubelet
    mode: "0644"
    owner: root
    group: root
  become: true

- name: "Configure cri-tools with selected CRI: {{ kubeadm_cri_type }}"
  template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml
    mode: "0644"
    owner: root
    group: root
  become: true

- name: Check if kubectl autocompletion exists
  stat:
    path: /etc/bash_completion.d/kubectl
  register: _kubectl_autocompletion

- name: Enable kubectl autocompletion
  command: kubectl completion bash > /etc/bash_completion.d/kubectl
  become: true
  when: _kubectl_autocompletion.stat.exists

- name: Check if kubeadm autocompletion exists
  stat:
    path: /etc/bash_completion.d/kubeadm
  register: _kubeadm_autocompletion

- name: Enable kubeadm autocompletion
  command: kubeadm completion bash > /etc/bash_completion.d/kubeadm
  become: true
  when: _kubeadm_autocompletion.stat.exists

- name: Create custom conf dir
  file:
    path: /etc/kubernetes/custom_configs
    state: directory
    owner: root
    group: root
    mode: "0644"
  become: true
