- name: generate random certificate key
  shell: kubeadm certs certificate-key
  register: certificate_key
  become: yes
  when: '"module_k8s_master_nodes_0" in group_names'

- name: copy kubeadm init config
  template:
    src: kubeadm_init.yml.j2
    dest: /etc/kubernetes/custom_configs/kubeadm_init.conf
  become: yes
  when: '"module_k8s_master_nodes_0" in group_names'

- name: kubeadm init
  shell: >
    kubeadm init --config /etc/kubernetes/custom_configs/kubeadm_init.conf
    --upload-certs
  become: yes
  when: '"module_k8s_master_nodes_0" in group_names'

- name: upload secret cloud.conf
  template:
    src: cloud.conf.j2
    dest: /tmp/cloud.conf
  when: '"module_k8s_master_nodes_0" in group_names'

- name: kubeadm load cloud.conf as secret
  shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf create secret -n kube-system generic cloud-config --from-file=/tmp/cloud.conf
  become: yes
  when: '"module_k8s_master_nodes_0" in group_names'

- name: create RBAC resources and openstack-cloud-controller-manager deamonset
  shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/manifests/controller-manager/{{ item }}
  loop:
    - cloud-controller-manager-roles.yaml
    - cloud-controller-manager-role-bindings.yaml
    - openstack-cloud-controller-manager-ds.yaml
  become: yes
  when: '"module_k8s_master_nodes_0" in group_names'

- name: create auth token
  shell: kubeadm token create
  register: token
  become: yes
  when: '"module_k8s_master_nodes_0" in group_names'

- name: calculate discovery token ca cert hash
  shell: >
    openssl x509 -in /etc/kubernetes/pki/ca.crt -pubkey -noout |
    openssl pkey -pubin -outform DER |
    openssl dgst -sha256 | awk '{print $2}'
  register: discovery_token_ca_cert_hash
  become: yes
  when: '"module_k8s_master_nodes_0" in group_names'

- name: copy kubeadm join config
  template:
    src: kubeadm_join.yml.j2
    dest: /etc/kubernetes/custom_configs/kubeadm_join.conf
  become: yes
  when: ("module_k8s_master_nodes_0" not in group_names)
    and ("module_k8s_worker_nodes" not in group_names)

- name: join master nodes
  shell: >
    kubeadm join --config /etc/kubernetes/custom_configs/kubeadm_join.conf
  become: yes
  when: ("module_k8s_master_nodes_0" not in group_names)
    and ("module_k8s_worker_nodes" not in group_names)
