- name: Creates .kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0600"
  become: yes

- name: delete auth token
  shell: kubeadm token delete {{ hostvars[groups['module_k8s_master_nodes_0'][0]]['token']['stdout'] }}
  run_once: True
