---
- name: Creates .kube directory
  file:
    path: ~/.kube
    state: directory
    owner: root
    group: root
    mode: "0700"
  become: true
- name: Copy file with owner and permissions
  copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    owner: root
    group: root
    mode: "0600"
  become: true
