- name: Install cilium cli
  ansible.builtin.unarchive:
    src: https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  become: yes

- name: enable cilium autocompletion
  shell: cilium completion bash > /etc/bash_completion.d/cilium
  become: yes

- name: install cilium
  shell: >
    cilium install --config k8s-api-server=https://{{ control_plane_endpoint }}:6443
    --config kube-proxy-replacement=strict --config cluster-pool-ipv4-mask-size={{ cluster_pool_ipv4_mask_size }}
    --config cluster-pool-ipv4-cidr={{ cluster_pool_ipv4_cidr }}  --wait-duration 100s
  run_once: True
