---
- name: Install cilium cli
  unarchive:
    src: "https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: true
  become: true

- name: Enable cilium autocompletion # noqa no-changed-when
  shell: cilium completion bash > /etc/bash_completion.d/cilium
  become: true

- name: Install cilium # noqa no-changed-when
  shell: >
    cilium install --config k8s-api-server=https://{{ kubeadm_control_plane_endpoint }}:6443
    --config kube-proxy-replacement=strict --config cluster-pool-ipv4-mask-size={{ kubeadm_cluster_pool_ipv4_mask_size }}
    --config cluster-pool-ipv4-cidr={{ kubeadm_cluster_pool_ipv4_cidr }}  --wait-duration 100s
  run_once: true
  become: true
