---
- hosts: module_k8s_master_nodes:module_k8s_worker_nodes:module_k8s_fip_jumphost
  tasks:
    - import_tasks: 01_prepare.yml

- hosts: module_k8s_master_nodes:module_k8s_worker_nodes
  tasks:
    - import_tasks: 02_install_kubetools.yml

- import_tasks: 03_provision_kubeadm.yml
  run_once: true
  delegate_to: "{{ groups['module_k8s_master_nodes'][0] }}"

# TODO: check if node needs to be added and then generate new cert + token

- hosts: module_k8s_master_nodes_0
  tasks:
    - block:
        - name: Generate random certificate key
          shell: kubeadm init phase upload-certs --upload-certs | tail -n 1
          register: certificate_key
          become: true

        - name: Create auth token
          command: kubeadm token create
          register: token
          become: true

        - name: Calculate discovery token ca cert hash
          shell: >
            openssl x509 -in /etc/kubernetes/pki/ca.crt -pubkey -noout |
            openssl pkey -pubin -outform DER |
            openssl dgst -sha256 | awk '{print $2}'
          register: discovery_token_ca_cert_hash
          become: true

        # Register do not work when using delegate_facts
        - name: Set facts
          set_fact:
            certificate_key: "{{ certificate_key }}"
            token: "{{ token }}"
            discovery_token_ca_cert_hash: "{{ discovery_token_ca_cert_hash }}"

      # end block
      # By default facts are assing to current host
      delegate_facts: true

- hosts: module_k8s_master_nodes:module_k8s_worker_nodes:!module_k8s_master_nodes_0
  tasks:
    - import_tasks: 04_join_claster.yml

- hosts: module_k8s_master_nodes_0
  tasks:
    - name: Delete auth token # noqa no-changed-when
      command: "kubeadm token delete {{ token.stdout }}"
      become: true

- hosts: module_k8s_master_nodes
  tasks:
    - import_tasks: 05_copy_kube_config.yml

- hosts: module_k8s_master_nodes
  tasks:
    - import_tasks: 06_cilium.yml
      when: >
        kubeadm_install_cilium | bool
