---
- import_tasks: 01_prepare.yml
- import_tasks: 02_install_kubetools.yml

- import_tasks: 03_provision_kubeadm.yml
  when: inventory_hostname == groups['kubeadm_masters'][0]

# TODO: check if node needs to be added and then generate new cert + token

- block:
    - name: Generate random certificate key
      shell: kubeadm init phase upload-certs --upload-certs | tail -n 1
      register: certificate_key
      become: true

    - name: Create auth token
      command: kubeadm token create
      register: token
      become: true

    - name: Calculate discovery token ca cert hash
      shell: >
        openssl x509 -in /etc/kubernetes/pki/ca.crt -pubkey -noout |
        openssl pkey -pubin -outform DER |
        openssl dgst -sha256 | awk '{print $2}'
      register: discovery_token_ca_cert_hash
      become: true

    # Register do not work when using delegate_facts
    - name: Set facts
      set_fact:
        certificate_key: "{{ certificate_key }}"
        token: "{{ token }}"
        discovery_token_ca_cert_hash: "{{ discovery_token_ca_cert_hash }}"

  # end block
  run_once: true
  delegate_to: "{{ groups['kubeadm_masters'][0] }}"
  # By default facts are assing to current host
  delegate_facts: true

- import_tasks: 04_join_claster.yml
  when: >
    (inventory_hostname in groups['kubeadm_masters'] or
    inventory_hostname in groups['kubeadm_workers']) and
    inventory_hostname != groups['kubeadm_masters'][0]

- name: Delete auth token  # noqa no-changed-when
  command: "kubeadm token delete {{ token.stdout }}"
  become: true
  run_once: true
  delegate_to: "{{ groups['kubeadm_masters'][0] }}"

- import_tasks: 05_copy_kube_config.yml
  when: inventory_hostname in groups['kubeadm_masters']

- import_tasks: 06_cilium.yml
  when: >
    cf_kubeadm_install_cilium | bool and
    inventory_hostname in groups['kubeadm_masters']
